import type { Metadata } from 'next';
import { Poppins as FontSans, Playfair as FontSerif } from 'next/font/google';
import localFont from 'next/font/local';

import './globals.css';
import { cn } from '@/lib/utils';
import { ThemeProvider } from '@/components/theme-provider';

const fontSans = FontSans({
	subsets: ['latin'],
	weight: ['300', '400', '500', '600', '700'],
	variable: '--font-sans',
});
// const fontSerif = FontSerif({
// 	subsets: ['latin'],
// 	weight: ['300', '400', '500', '600', '700'],
// 	variable: '--font-serif',
// });
const recoleta = localFont({
	src: [{ path: '../public/fonts/recoleta-regular.otf', weight: '400' }],
	variable: '--font-serif',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={cn(
					'min-h-screen bg-background font-sans antialiased',
					fontSans.variable,
					// fontSerif.variable
					recoleta.variable
				)}
			>
				<ThemeProvider
					attribute='class'
					defaultTheme='system'
					enableSystem
					disableTransitionOnChange
				>
					{children}
				</ThemeProvider>
			</body>
		</html>
	);
}
