import { signOut } from '@/actions/signin-action';
import SideBarNav from '@/components/nav/SideBarNav';
import TopNav from '@/components/nav/TopNav';
import { getUser } from '@/lib/db';
import type { Metadata } from 'next';

export const metadata: Metadata = {
	title: 'Admin Dash',
	description: 'Generated by create next app',
};

export default async function AuthenticatedLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const user = await getUser();
	if (user && user?.role === 'user') await signOut();

	return (
		<>
			<SideBarNav />
			<div className='md:ml-56'>
				<TopNav />

				<main className='p-6'>{children}</main>
			</div>
		</>
	);
}
